[browser]
# edge | chrome | firefox
name = edge
headless = false

[timeouts]
# segundos — usado em WebDriverWait (esperas explícitas)
explicit_wait = 20

[app]
base_url = https://hom-mi.levesaude.com.br
